---
title: "Project R Skills"
date: "March 2, 2021"
output: html_document
---

# Human Freedom of Different World Regions

```{r}
library(openintro)

library(tidyverse)
library(infer)
library(moderndive)
library(broom)

library(ggridges)
```


# Filter Out Certain Regions 

```{r}
hfi_ocean <- hfi %>% 
  filter(region == "Oceania")
  
```



# Visualize Relationship between Region & Human Freedom Score

```{r}
hfi %>% 
  ggplot(aes(y = region, x = hf_score, fill = region)) +
  geom_boxplot() + 
  theme(legend.position = "none")

hfi %>% 
  ggplot(aes(y = region, x = hf_score, fill = region)) +
  geom_density_ridges() + 
  theme(legend.position = "none")

```



# Incorporate Year into the Visualization

```{r}
hfi %>% 
  ggplot(aes(y = region, x = hf_score, fill = as.factor(year))) +
  geom_boxplot() + 
  theme(legend.position = "none") 

hfi %>% 
  ggplot(aes(y = region, x = hf_score, fill = region)) +
  geom_density_ridges() + 
  facet_wrap(vars(year)) + 
  theme(legend.position = "none")

```


# Fit an ANVOA Model 

```{r}
hfi_anova <- aov(hf_score ~ region, data = hfi) 

hfi_anova %>% 
  tidy()

```


# Inspect Model Conditions 

```{r}
hf_info <- augment(hfi_anova)

hf_info %>% 
  ggplot(aes(x = .resid)) + 
  geom_histogram(binwidth = 0.25)


hf_info %>% 
  ggplot(aes(x = .fitted, y = .resid)) + 
  geom_point() + 
  geom_hline(yintercept = 0, color = "red")

```


# Using a Simulation-based Method Instead 


```{r}
obs_F <- hfi %>% 
  specify(___) %>% 
  calculate(stat = ___)

null_dist <- hfi %>% 
  specify(___) %>% 
  hypothesise(___) %>% 
  generate(___) %>% 
  calculate(___)

null_dist %>% 
  visualise()
```


## Get the p-value! 

```{r}
get_p_value(null_dist, obs_stat = obs_F, direction = "greater")
```


# Which Countries Differ? 

```{r}
hfi %$%
  pairwise.t.test(x = ___, g = ___, p.adjust.method = "bonferroni")
```



