---
title: "Final Exam - Stat 313"
date: "November 24, 2020"
output:
  pdf_document: default
  html_document: default
---

# Statistical Inference - Question Bank 

1. Explain to someone who has never taken a statistics course what a p-value is. 

_Possible follow-up questions:_ 

- A p-value is often reported as a percentage. What does that percentage p-value mean?
- How is a p-value calculated? 
- What does a small / large p-value suggest? 


\vspace{0.25cm}

2. Explain to someone who has never taken a statistics course what a confidence interval is. 

_Possible follow-up questions:_ 

- What value does a confidence interval hope to capture?
- What does it mean to say you're "95% confident"? 
- How is a confidence interval calculated? 


\vspace{0.25cm}

3. It is very likely researchers in your field are familiar with parametric tests (e.g. $t$-test, $F$-test) but are not familiar with simulation based methods (e.g. randomization test, bootstrap confidence interval). Explain to someone in your field the similarities and differences between these two methods. 

_Possible follow-up questions:_ 

- How does a t-test calculate a p-value / confidence interval? 
- Why would a researcher choose to use one method over the other? 
- How are the data "simulated" to obtain a permutation distribution? 
- What are similarities and differences between a permutation distribution and a t-distribution?

\vspace{0.25cm}

4. Large portions of the scientific community are pushing to eliminate p-value thresholds for publication of scientific research. What is the role of a p-value threshold (e.g. 0.05) in hypothesis testing? What are the benefits and costs of eliminating p-value thresholds? 

_Possible follow-up questions:_ 

- What does a p-value of 0.05 mean?
- Does a p-value less than 0.05 demonstrate that the findings of a study are "significant"? 
- What could replace a p-value threshold in determining the "significance" of a study? 

\vspace{0.25cm}

5. In the last lab assignment (Inference for Linear Regression), you used a bootstrap distribution to estimate a plausible range of values for the population slope. What is the key assumption behind a bootstrap distribution? Why was it not necessary to create a bootstrap distribution to estimate a range of values for the population slope?

_Possible follow-up questions:_ 

- What were the observations in the data from the lab assignment? 
- What value was recorded in each row of the data?
- What population were we interested in? 

\vspace{0.25cm}

# Linear Models - Question Bank

\vspace{0.25cm}

1. Suppose a researcher performs a one-way ANOVA and finds strong evidence to reject the null. They are interested in reporting which groups are "significantly" different from each other and are planning to perform tests for a difference in means for all of the groups that appear to be different. Explain to this individual the issues with this analysis strategy and propose an alternative strategy they should take. 

_Possible follow-up questions:_ 

- What issue is there will performing lots of tests for a difference in means? 
- How does the post-hoc test control the Type I error rate? 
- How do you determine if a difference in means is "significant" with a post-hoc test?

\vspace{0.25cm}

2. When the conditions for a linear regression are violated, how is the associated p-value and confidence interval impacted? How do these impacts differ for simulation based methods versus parametric methods? 

_Possible follow-up questions:_ 

- What are the conditions of a linear regression?
- If these conditions are violated, what happens to the p-value? The confidence interval? 
- What conditions do simulation based methods have? How does this differ from a t-test? 
- In the lab, we saw that with violated conditions we obtained contradictory findings from a randomization distribution and a bootstrap distribution. Would this same thing have happened if we had used a t-test instead? 

\vspace{0.25cm}

3. A one-way ANOVA compares the means of three or more groups, and summarizes these differences with an F-statistic. What are the components of an F-statistic and what does each term symbolize in terms of the variability of the responses? 

_Possible follow-up questions:_ 

- What does the mean square of the groups represent? How is it calculated?
- What does the mean square of the errors represent? How is it calculated? 
- If I were to obtain a large F-statistic, what does that indicate about the mean square of our groups relative to the mean square of the error?
- What would you expect to see in a data visualization for a one-way ANOVA with a large F-statistic? 

\vspace{0.25cm}

4. What are the similarities and differences between a two-way ANOVA model and a multiple linear regression? What does it mean to have "parallel lines" in a two-way ANOVA? What does it mean to have "different slopes" in a two-way ANOVA?  

_Possible follow-up questions:_ 

- How are the "slopes" in a two-way ANOVA model formed? 
<!-- - What would you look for in a visualization of a two-way ANOVA model to decide if the "slopes" are different?  -->
- What do parallel slopes / different slopes indicate about the relationship between the explanatory variables and the response? 
- How does a two-way ANOVA model summarize the relationships between variables? How does this differ from a multiple linear regression? 

\vspace{0.25cm}

5. Prior to this year, it was fairly common for medical studies to have a lack of representation of women and people of color (and women of color). Suppose a researcher was interested in assessing the relationship between race and age on the metabolic rates of women. The researcher categorized race and age as follows: 

* Black, Hispanic, American Indian or Alaska Native, Asian, Native Hawaiian or Pacific Islander, White
 
* 20 - 30, 30 - 40, 40 - 50, 50 - 60, 60 - 70, 70 - 80

The researcher recruited one woman from each intersecting group (e.g. Black and 30-40).  When testing for an interaction between race and age on metabolic rates, the researcher obtained the following degrees of freedom for their test. What is the issue? What can the researcher do to assess the relationship between these variables and the metabolic rate?  

| term     | degrees of freedom  |  
| -------- |:-------------------:|  
| race     | 5  |  
| age      | 5  |  
| race:age | 25 |  
| error    | 0  | 

_Possible follow-up questions:_ 

- Why does the ANOVA table have 0 degrees of freedom in the error?
- What issues does this cause for the hypothesis tests?
- What are ways the researcher could add degrees of freedom in the error?
- If the researcher could not add subjects in their study, what type of statistical model could they fit? 