---
title: ".hand[What is a **facet**?]"
output:
  xaringan::moon_reader:
    lib_dir: libs
    css: ["xaringan-themer.css", "slide-style.css"]
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
      ratio: '16:9'
      slideNumberFormat: |
        <div class="progress-bar-container">
          <div class="progress-bar" style="width: calc(%current% / %total% * 100%);">
          </div>
        </div>
---

```{r setup, include = FALSE}
library(tidyverse)
library(gridExtra)
library(flair)

knitr::opts_chunk$set(echo = TRUE, 
                      message = FALSE, 
                      warning = FALSE)

mpg <- mpg %>% 
  mutate(cyl = as.factor(cyl))
```


.larger[We've added a second variable by filling the bars with different 
colors...]

---

.larger[What is a **facet**?]

.pull-left-narrow[
.large[A *facet* is a subplot for each subset of a dataset.]
]

.pull-right-wide[
```{r, echo = FALSE, fig.height = 8, fig.width = 12}
ggplot(data = mpg) + 
  geom_bar(mapping = aes(y = manufacturer, 
                         fill = cyl)
           ) +  
  facet_wrap(~ drv)
```
]

---

.larger[We can facet by one variable with **facet_wrap()**]

</br>
</br>

<center>

```{r wrap, eval = FALSE, echo = FALSE}
ggplot(data = mpg) + 
  geom_bar(mapping = aes(y = manufacturer, 
                         fill = cyl)
        ) +  
  facet_wrap(~ drv)
```

```{r, echo = FALSE}
decorate("wrap", eval = FALSE) %>% 
  flair(pattern = "facet_wrap") %>% 
  flair(pattern = "~ cyl", color = "red")
```


---

```{r, echo = FALSE, fig.align = 'center', fig.width = 10, fig.height = 8}
ggplot(data = mpg) + 
  geom_bar(mapping = aes(y = manufacturer, 
                         fill = cyl)
        ) +  
  facet_wrap(~ drv)
```

---

.larger[We can facet by two variables with **facet_grid()**]

</br>
</br>

<center>

```{r grid, eval = FALSE}
ggplot(data = mpg) + 
  geom_bar(mapping = aes(y = manufacturer)
           ) +  
  facet_grid(cyl ~ drv)
```

---

```{r, echo = FALSE, fig.align = 'center', fig.width = 12, fig.height = 8}
ggplot(data = mpg) + 
  geom_bar(mapping = aes(y = manufacturer)
        ) +  
  facet_grid(cyl ~ drv)
```

