---
title: "Midterm Exam - Stat 313"
date: "October 25 & 26, 2021"
output:
  pdf_document: default
  html_document: default
---

# Linear Models - Question Bank

You will be asked one randomly selected question from this bank of questions
during your oral exam. 

1. A linear regression is one type of model in the broad class of "linear
models." What are the characteristics of these linear models? 

\vspace{0.25cm}

2. Describe to someone who has never taken a statistics course the difference 
between simple linear regression and multiple linear regression. 

\vspace{0.25cm}

3. What are the strengths and weaknesses of linear regression?  

<!-- \vspace{0.25cm} -->

<!-- 4. Many disciplines employ regression, but do not check the model conditions.  -->
<!-- Why should we care about the model conditions? What are the implications of not  -->
<!-- checking these conditions?   -->

\vspace{0.25cm}

4. Some textbooks state that regression should not be used if there are
"outliers" in the data. Why is this an important condition to consider? What are
the implications of removing every "outlier" from a dataset?  

\vspace{0.25cm}

5. Most people are familiar with the saying that "correlation does not imply 
causation." However, when some researchers find a strong correlation between 
their explanatory and response variables (r > 0.8), they often interpret the 
relationship as "larger values in x **_lead to_** larger values in y." What is
an issue with this interpretation? In this scenario, what could researchers 
conclude?  

\newpage

# Additional Topics - Question Bank

You will be asked one randomly selected question from this bank of questions
during your oral exam.

\vspace{0.25cm}

__Statistical Models__ 

1. Describe to someone who has never taken a Statistics course what the
principle of parsimony (or Occam's razor) is. 

\vspace{0.25cm}

<!-- 2. Describe to someone who has never taken a Statistics course what Simpson's -->
<!-- paradox is.  -->

<!-- \vspace{0.25cm} -->

<!-- 3. How would you determine if your statistical model should be used for  -->
<!-- predicting what could be expected to happen for a **_new_** dataset?  -->

<!-- \vspace{0.25cm} -->

__Reproducibility__ 

2. Much of what we have done thus far using `R` and R Markdown documents could
have been done using Excel and Word. What are the benefits of using `R` and 
R Markdown documents? What are the costs?  

\vspace{0.25cm}

__Data Visualization__

3. We have spent a great deal of time producing and critiquing data
visualizations, and have yet to discuss statistical testing (e.g. 
hypothesis tests and p-values). What information can a data visualization
provide you that a data summary or a statistical test cannot?   

<!-- What would you say to someone that said someone could manipulate a visualization to say whatever they want, but a statistical analysis doesn't lie? -->

\vspace{0.25cm}

__Study Design__

4. Random samples and experiments are often thought of as the "gold standard" of 
study design. Why are these aspects of a study so highly valued? What
difficulties may researchers encounter when attempting to utilize these 
designs in their study? 

<!-- \vspace{0.25cm} -->

<!-- 5. What is the purpose of blocking in a study? If an experiment fails to block  -->
<!-- on a variable that influences the response, what are the implications for the  -->
<!-- inference of the study?   -->

__Philosophy__

5. How is statistics used in the generation of scientific knowledge? How is dichotomous thinking used in statistics? How is objectivity related to each of 
these areas? 
