---
title: 'Stat 313: Midterm Project'
author: "Names here! Include both first and last names!"
date: "Date here!"
output: html_document
---

```{r setup, include = FALSE}
## Do not change this code chunk! 
## This has settings for how I want your report to look!

knitr::opts_chunk$set(echo = FALSE, 
                      fig.align = "center", 
                      message = FALSE, 
                      warning = FALSE)
## This makes it so your code will not print to the page, which makes your report look more professional!
## Additionally, there will be no messages or errors output for your models an / or visualizations. 
## And your figures will be centered on the page. 
```

```{r, include = FALSE}
## Package for the dataset (evals)
library(openintro)

# Package for the functions we want
library(tidyverse)

# Package for the nice looking regression tables
library(moderndive)
```


# Introduction 
<!-- TODO: -->
<!-- 1. Include a background of the data and the unit of study. -->

<!-- 2. Articulate the research question of interest -- be specific! -->





# Statistical Methods
<!-- TODO: -->
<!-- 1. Describe the response and explanatory variables. -->

<!-- 2. Create a summary table of the mean and median course evaluation scores
and average beauty scores -->

<!-- 3. Create visualizations investigating the relationship(s) of interest.  -->

<!-- 4. Describe what you see in the visualizations, making direct references to the plots! -->

<!-- 5. Outline what statistical method will be used to address the question of interest, and why this method is appropriate. -->




# Summary of Statistical Findings 
<!-- TODO: -->
<!-- 1. Provide conclusion for questions of interest -- referencing 
visualizations AND the statistical model. -->

<!-- 2. Using the coefficients you obtained, write out the estimated regression equation for each level of your categorical variable.  -->

<!-- 3. Interpret in the context of the data the coefficients from each regression equation. -->
  



# Scope of Inference 
<!-- TODO: -->
<!-- 1. Who can the results of this investigation be applied to? Why?  -->

<!-- 2. What can be said about the relationship between the average SAT math and 
SAT verbal scores? Why? -->

<!-- 3. Make sure your statements are in the context of this study!  -->





