---
title: "Stat 313: Project 2"
author: "Names here! Include both first and last names!"
date: "Date submitted here!"
output: html_document
---

```{r setup, include = FALSE}
## Do not change this code chunk! 
## This has settings for how I want your report to look!

knitr::opts_chunk$set(echo = FALSE, 
                      message = FALSE, 
                      warning = FALSE)
## This makes it so your code will not print to the page, which makes your report look more professional! 
```

```{r, include = FALSE}
## Insert the code to include the packages you wish to use here!



## Read in the data! 
## To use similar code to the previous project, store the data file in the SAME folder as this RMarkdown document

lungs <- read_csv("[DIRECTIONS TO DATA HERE]")
```


```{r, include = FALSE}
## This is code you should run to get the ages of the study participants to be in the right order 
## This makes it so your facets / legend are in the correct order of ages
lungs <- lungs %>%
  mutate(age = factor(age, levels = c("toddler", "preschooler", 
                                      "middle childhood", "pre-teen", 
                                      "teenager")
                      )
         )
```


# Introduction 
<!-- TODO: -->
<!-- 1. Include a background description of the data. -->
<!-- 2. Articulate the research question of interest -- be specific! -->



# Statistical Methods
<!-- TODO: -->
<!-- 1. Describe the response and explanatory variables. -->
<!-- 2. Create a table summarizing the number of observations for every combination of smoking and sex.  -->
<!-- 3. Create a visualization investigating the relationship of interest.  -->
<!-- 4. Discuss a potential confounding variable impacting this relationship.  -->
<!-- 5. Create a visualization investigating the relationship of interest, accounting for the confounding variable.  -->
<!-- 6. Describe what statistical method will be used to address the question of interest, and why this method is appropriate.-->
<!-- 7. Check model conditions for statistical model chosen. Include all necessary plots! -->



# Summary of Statistical Findings 
<!-- TODO: -->
<!-- 1. Provide conclusion for questions of interest -- referencing visualizations and statistical model. -->
<!-- 2. Interpret the p-value associated with "smoke" in the ANOVA table -- in the context of these data.  -->



# Study Design
<!-- TODO: -->
<!-- 1. Discuss the possible issue(s) with asking about smoking on a survey.  -->
<!-- 2. Discuss how these issues might manifest in the data collected for this study.  -->



# Scope of Inference 
<!-- TODO: -->
<!-- 1. Who can the results of this investigation be applied to? Why?  -->
<!-- 2. What can be said about the relationship between smoking and lung 
expiratory volume? Why? -->


