---
title: "`r emo::ji('scientist')` P-values & Hypothesis Tests"
format: 
  revealjs:
    theme: dark
    self-contained: true
editor: visual
---

::: {style="font-size: 4em; color: #FFFFFF;"}
you...
:::

::: {style="font-size: 1.25em; color: #FFFFFF;"}
- understand the importance of sampling variability
- know about using confidence intervals to estimate a range of plausible values
for the population parameter
- want to know how p-values fit in
:::

##  {background-color="#B6CADA"}

::: {style="font-size: 2.5em; color: #000000;"}
What if I want to know if the population parameter differs from a 
specific value?
:::

. . .

<center>
::: {style="font-size: 2em; color: #0F4C81;"}
Hypothesis test!
:::
</center>

##

::: {style="font-size: 3em; color: #FFFFFF;"}
Goal:
:::

::: {style="font-size: 1.5em; color: #FFFFFF;"}
Assess how different what we saw in our data is from what could have
happened if the null hypothesis was true
:::

##  {background-color="#B6CADA"}

::: {style="font-size: 3em; color: #000000;"}
Permutation Distribution
:::

. . .

::: {style="font-size: 1.25em; color: #000000;"}
Uses the original sample to generate new samples that might have occurred if the null hypothesis was true. 
:::

. . .

::: {style="font-size: 1.25em; color: #0F4C81;"}
We can use the statistics from these samples to approximate the
true sampling distribution under the null!
:::

##

::: {style="font-size: 2.5em; color: #FFFFFF;"}
**What could have happened if the null was true?**
:::

. . .

::: {style="font-size: 0.75em; color: #FFFFFF;"}
Like before, we are interested in knowing how a statistic varies from sample to sample.
:::

. . .

::: {style="font-size: 0.75em; color: #FFFFFF;"}
Again, knowing a statistic's behavior helps us make better / more informed decisions!
:::

. . .

::: {style="font-size: 0.75em; color: #FFFFFF;"}
This helps us know what statistics are more or less likely to occur if the null hypothesis is true.
:::

##  {background-color="#B6CADA"}

::: {style="font-size: 4em; color: #000000;"}
p-values
:::

. . .

::: {style="font-size: 1.5em; color: #000000;"}
Quantify how "surprising" what we saw in our data is, if the null
hypothesis was true
:::

##

::: {style="font-size: 3em; color: #FFFFFF;"}
**Permutation Resamples**
:::

. . .

From your original sample, separate the $x$ values from the $y$ values. 

. . .

Create new ordered pairs by randomly pairing $x$ values with $y$ values (permuting the labels). 

. . .

<center>
::: {style="font-size: 1.5em; color: #0F4C81;"}
**This is your _permuted resample_!** 
:::
</center>

##

::: {style="font-size: 3em; color: #FFFFFF;"}
**Permuted Statistics**
:::

Repeat this process many, many times. 

. . .

Calculate a numerical summary (e.g., mean, median) for each permuted resample. 

. . .

<center>
::: {style="font-size: 1.5em; color: #0F4C81;"}
**These are your _permuted statistics_!** 
:::
</center>

##  {background-color="#B6CADA"}

::: {style="font-size: 3em; color: #000000;"}
Permutation Distribution
:::

. . .

> [*definition*: a distribution of the]{style="color: #000000;"} [*permuted statistics*]{style="color: #0F4C81;"}
[from every]{style="color: #000000;"} [*permuted resample*]{style="color: #0F4C81;"}

. . .

Displays the variability in the statistic that could have happened with repeated sampling, **if the null hypothesis was true**.

. . .

::: {style="color: #0F4C81;"}
Approximates the true sampling distribution under the
null!
:::

##

::: {style="font-size: 2em; color: #FFFFFF;"}
How do I get my p-value?
:::

. . .

::: {style="font-size: 1.25em; color: #0F4C81;"}
We compare the observed statistic with the statistics produced assuming the null hypothesis was true.
:::

. . .

</br>

::: {style="font-size: 1.25em;"}
A p-value summarizes the [**probability**]{style="color: #0F4C81;"}
 of obtaining a sample statistic [as or more extreme than what we observed]{.underline}, [**if the null hypothesis was true**]{style="color: #0F4C81;"}.
:::

##

::: {style="font-size: 3em; color: #FFFFFF;"}
Your turn!
:::

::: {style="font-size: 1.5em; color: #FFFFFF;"}
**What is one similarity and one difference between**
:::

::: columns
::: {.column width="45%"}

::: {style="font-size: 1.5em; color: #0F4C81;"}
a permutation distribution
:::

:::

::: {.column width="5%"}
:::

::: {.column width="45%"}

::: {style="font-size: 1.5em; color: #0F4C81;"}
a bootstrap distribution
:::

:::
:::
