---
title: "Stat 313: SAT Exploration"
date: "January 31"
output: html_document
---

```{r setup, include = FALSE}
## Do not change this code chunk! 
## This has settings for how I want your report to look!

knitr::opts_chunk$set(echo = FALSE)
## This makes it so your code will not print to the page, which makes your report look more professional! 
```

```{r, include = FALSE}
## Insert the code to include the packages you wish to use here!


```


```{r, include = FALSE}
## Average SAT Math and Verbal Scores for every state
## Includes average scores for different income levels
sat <- read_csv("school_scores.csv") %>%
  select(Year, State.Code, State.Name,
        starts_with("Family Income")
  ) %>% 
  select(-contains("Test-takers"))

sat <- sat %>% 
  pivot_longer(cols = starts_with("Family Income"), 
               names_to = c("Income", "Exam"),
               names_pattern = "Family Income\\.(.*)\\.(.*)",
               values_to = "Average Score"
  ) %>% 
  pivot_wider(names_from = Exam, 
              values_from = `Average Score`)

```

```{r}
## Trying a different pivot 
sat2 <- read_csv("school_scores.csv") %>%
  select(Year, State.Code, State.Name,
        starts_with("Family Income")
  ) %>% 
  select(-contains("Test-takers"))

sat2 <- sat2 %>% 
  pivot_longer(cols = starts_with("Family Income"), 
               names_to = c("Income", "Exam"),
               names_pattern = "Family Income\\.(.*)\\.(.*)",
               values_to = "Average Score"
  )

```



# Introduction 
<!-- TODO: -->
<!-- 1. Include a background of the data. -->
<!-- 2. Articulate the research question of interest -- be specific! -->





# Statistical Methods
<!-- TODO: -->
<!-- 1. Describe the response and explanatory variables. -->
<!-- 2. Create visualizations investigating the relationships of interest.  -->
<!-- 3. Describe what statistical method will be used to address the question of interest, and why this method is appropriate. -->
<!-- 4. Check model conditions for statistical model chosen. Include all necessary plots! -->

```{r}
sat %>% 
  ggplot(aes(x = Verbal, y = Math, color = Income)) + 
  geom_point(alpha = 0.5) +
  geom_parallel_slopes()
```




# Summary of Statistical Findings 
<!-- TODO: -->
<!-- 1. Provide conclusion for questions of interest -- referencing visualizations and statistical model. -->
<!-- 2. Interpret each of the coefficients from the statistical model -- in the context of these data.  -->





# Scope of Inference 
<!-- TODO: -->
<!-- 1. Who can the results of this investigation be applied to? Why?  -->
<!-- 2. What can be said about the relationship between the percentage of students  -->
<!-- receiving grants and the percentage of Black graduates? Why? -->





