---
title: "Connecting Statistical Models -  Small Group Collaboration Session 9"
date: November 19, 2020
output: ioslides_presentation
---

<style type="text/css">
slides > slide:not(.nobackground):after {
  content: '';
}
</style>

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = FALSE, 
                      message = FALSE, 
                      fig.width = 4, 
                      fig.height = 4)
library(tidyverse) 
library(palmerpenguins)
library(gridExtra)
library(openintro)
library(infer)
library(broom)
library(RColorBrewer)
```

## ANOVA & MLR 

</br> 

In a two-way ANOVA, what are the two types of models you can fit? 

</br> 

How are these models similar / different from the multiple linear regression models we discussed? 

</br> 

## Inspecting MLR Models 

<!-- In a simple linear regression, if the slope is close to 0, what model would we fit instead?  -->

<!-- </br> -->

In a multiple linear regression, if the slopes of every group are the same, what model would we fit instead?  

- How would you justify this choice? 

</br>

In a parallel lines multiple linear regression, if the slopes of every group are 0, what model would we fit instead?  



## Inspecting ANOVA Models  

Why would a researcher choose to use a one-way ANOVA instead of a simple linear regression?  

</br> 

Why would a researcher choose to use a two-way ANOVA instead of a multiple linear regression? 

## Study Design and ANOVA 

</br> 

Why would a study employ blocking?  

</br> 

If the blocking variable was included in an ANOVA, would you expect for it to be "statistically significant"? 

## Blocking and Two-Way ANOVA 

Suppose the study yields the following ANOVA table. 


| term            | statistic     | p-value|
| --------------- |:-------------:| ------:|
| treatment       | 4.25          | 0.035  |
| block           | 3.5           | 0.015  |
| treatment:block | 2.5           | 0.01   |

</br> 

Are there issues if there is evidence of an interaction between the blocking variable and the treatment?


