---
title: "SLR / MLR Project Data"
date: "10/18/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```


## Completion Data

```{r}
completion <- read_csv("completion/c2019_c.csv")

replace_0 <- function(x) ifelse(x == 0, NA, x)

completion <- completion %>% 
  select(university = UNITID, 
         degree = AWLEVELC,
         total_grad = CSTOTLT, 
         total_men = CSTOTLM, 
         total_women = CSTOTLW, 
         total_aian = CSAIANT, 
         total_asian = CSASIAT,
         total_black = CSBKAAT, 
         total_hisp = CSHISPT, 
         total_white = CSWHITT,
         total_nhpi = CSNHPIT) %>% 
  mutate_at(vars( starts_with("total_") ),
            replace_0) %>% 
  mutate(perc_men = total_men / total_grad * 100, 
       perc_women = total_women / total_grad * 100, 
       perc_aian = total_aian / total_grad * 100, 
       perc_asian = total_asian / total_grad * 100, 
       perc_black = total_black / total_grad * 100, 
       perc_hisp = total_hisp / total_grad * 100, 
       perc_white = total_white / total_grad * 100, 
       perc_nhpi = total_nhpi / total_grad * 100) %>% 
  mutate(degree = case_when(degree == "05" ~ "Bachelors", 
                            degree == "03" ~ "Associates", 
                            degree == "07" ~ "Masters", 
                            degree == "09" ~ "Doctorate")) %>% 
  drop_na()
```

## Financial Aid Data

```{r}
fin_aid <- read_csv("financial aid/sfa1819.csv")

fin_aid <- fin_aid %>% 
  select(university = UNITID,
         perc_undergrad_grants = UAGRNTP, 
         perc_undergrad_pell = UPGRNTP, 
         perc_undergrad_loans = UFLOANP)
```

## Grants Data

```{r}
grants <- read_csv("grants/gr2019_pell_ssl.csv")
```

## Outcomes Data

```{r}
outcomes <- read_csv("outcomes/om2019.csv")
```

## Joining Data on University ID

```{r}
## Join on UNITID column

aid_completion <- completion %>% 
  left_join(fin_aid, 
            by = "university") %>% 
  select(-total_grad, -total_men, -total_women, -total_aian, -total_asian, 
         -total_black, -total_hisp, -total_white, -total_nhpi) 

```

## Data Exploration 

```{r}
aid_completion %>%
  filter(degree != "Doctorate") %>% 
  ggplot(aes(y = perc_black, x = perc_undergrad_grants, color = degree)) + 
  geom_point() + 
  geom_smooth(method = "lm")
```


## Different Slopes Model 

```{r}
anova(
  lm(perc_women ~ perc_undergrad_grants*degree, data = aid_completion)
)
```



