---
title: "Final Day"
format: revealjs
editor: visual
---


.huge[Some Closing Thoughts...]

---


class: middle, inverse


.larger[I hope you leave this class understanding...] 

- Reproducibility is a foundational aspect to scientific research. 

- Data visualizations tell you a story, where statistical tests only tell you a
summary.  

- Multiple regression and two-way ANOVA are powerful tools to explore
multivariate relationships. 

- A well thought out study is more powerful than any statistical analysis. 

---

class: middle, center

.larger[The Discipline of Statistics]

.large[The field of Statistics was developed to evaluate evidence obtained from
data. Over the last century, the use of statistics has become embedded as a
component of the scientific process for many disciplines.]

---

class: middle

.larger[**Foundational ideas taught in statistics courses were invented by:**] 

- Francis Galton 
- Karl Pearson 
- Ronald Fisher

---

.large\[**Eugenics & Statistics**\]

</br>

*Ideally, statisticians would like to divorce these tools from the lives and times of the people who created them. It would be convenient if statistics existed outside of history, but that's not the case. Statistics, as a lens through which scientists investigate real-world questions, has always been smudged by the fingerprints of the people holding the lens. Statistical thinking and eugenicist thinking are, in fact, deeply intertwined, and many of the theoretical problems with methods like significance testing---first developed to identify racial differences---are remnants of their original purpose, to support eugenics.*

[How Eugenics Shaped Statistics](https://nautil.us/issue/92/frontiers/how-eugenics-shaped-statistics)

---

.larger[**Statistical Significance** -- The New "S" Word]

- "Significance, the new s-word, is overused and underdefined in the realm of
connecting statistical results to the underlying science."

- "When used in statistics, significant does not mean important or meaningful,
as it does in everyday speech."

- "I advocate a simple solution: Replace the s-word with words describing what
you actually mean by it."

---

class: inverse

.large\[**Moving to a World Beyond 0.05**\]

-   Accept & Acknowledge Uncertainty

-   Be Thoughtful

-   Be Open

-   Be Modest

---

class: middle, inverse

.larger[Remember to give yourself praise!]



