---
title: ".hand[ggplot2 first steps]"
output:
  xaringan::moon_reader:
    lib_dir: libs
    css: ["xaringan-themer.css", "slide-style.css"]
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
      ratio: '16:9'
      slideNumberFormat: |
        <div class="progress-bar-container">
          <div class="progress-bar" style="width: calc(%current% / %total% * 100%);">
          </div>
        </div>
---

```{r setup, include = FALSE}
library(ggplot2)
library(flair)
```


```{r, fig.align='center'}
ggplot(data = mpg) + 
  geom_bar(mapping = aes(y = manufacturer))
```

---

.larger[Start with a blank plot]

```{r, fig.height = 5, fig.align='center'}
ggplot(data = mpg)
```

---

class: middle, center 

.larger[Add (`+`) a `geom`]

</br> 
</br> 

```{r add, eval = FALSE, echo = FALSE}
ggplot(data = mpg) + 
  geom_bar()
```

```{r, echo = FALSE}
decorate("add", eval = FALSE) %>% 
  flair("+")
```

---

class: middle, center

.larger[Map variables to **aes**thetics]

.pull-left-wide[
```{r aes, eval = FALSE, echo = FALSE}
ggplot(data = mpg) + 
  geom_bar(mapping = aes(y = manufacturer))
```

```{r, echo = FALSE}
decorate("aes", eval = FALSE) %>% 
  flair("aes")
```
]

.pull-right[
```{r, echo = FALSE, fig.height = 4}
ggplot(data = mpg) + 
  geom_bar(mapping = aes(y = manufacturer))
```
]

---

class: middle, center

.larger[A reusable template]

</br>

```{r, eval = FALSE}
ggplot(data = <DATA>) + 
  <GEOM_FUNCTION>(mapping = aes(<MAPPINGS>))
```
