---
title: "Introduction to Multiple Linear Regression"
format: 
  revealjs:
    self-contained: true
editor: visual
---

```{r set-up}
#| include: false

library(tidyverse)
library(moderndive)
library(openintro)

```

##  {background-color="#D4D4D4"}

::: {style="font-size: 3em; color: #000000;"}
Before...
:::

```{r old-slr}
#| echo: false
ncbirths %>% 
  ggplot(mapping = aes(x = weeks, y = weight)) + 
  geom_jitter() + 
  geom_smooth(method = "lm") +
  labs(x = "Weeks of Gestation", 
       y = "Weight of Baby (lbs)")

```


##  {background-color="#D4D4D4"}

::: {style="font-size: 3em; color: #000000;"}
Now...
:::


```{r two-mlr}
#| echo: false

ncbirths %>% 
  ggplot(mapping = aes(x = weeks, y = weight, color = habit)) + 
  geom_jitter() + 
  geom_smooth(method = "lm") +
  labs(x = "Weeks of Gestation", 
       y = "Weight of Baby (lbs)", 
       color = "Mother Smoking Status")

```


##  {background-color="#B6CADA"}

</br>
</br>
<center>
::: {style="font-size: 6em; color: #000000;"}
How?
:::
</center>

##  {background-color="#D4D4D4"}

::: {style="font-size: 2em; color: #000000;"}
Offsets!
:::

```{r smoke-mlr}
#| eval: false
smoke_lm <- lm(weight ~ weeks * habit, data = ncbirths)

get_regression_table(smoke_lm)

```

```{r}
#| echo: false
smoke_lm <- lm(weight ~ weeks * habit, data = ncbirths)

get_regression_table(smoke_lm) %>% 
  select(term:std_error)
```

. . .

</br>

::: {style="font-size: 1.25em; color: #0F4C81;"}
What is the regression equation for non-smoker birthing people?
:::

. . .

::: {style="font-size: 1.25em; color: #0F4C81;"}
What is the regression equation for smoker birthing people?
:::

##  {background-color="#B6CADA"}

<center>
::: {style="font-size: 3em; color: #000000;"}
What if we have a second numerical explanatory variable?
:::
</center>

##  {background-color="#D4D4D4"}

```{r}
ncbirths %>% 
  ggplot(mapping = aes(x = weeks, y = weight, color = mage)) + 
  geom_jitter() + 
  geom_smooth(method = "lm") +
  labs(x = "Weeks of Gestation", 
       y = "Weight of Baby (lbs)", 
       color = "Mother's Age")

```

