---
title: "Assessing Normality & Equal Variance"
output: html_document
---

```{r}
## packages needed 
library(tidyverse)
library(openintro)
library(broom)
```

Step 1: Fit a multiple linear regression model 

```{r}
bty_score_lm <- lm(score ~ bty_avg + gender + bty_avg:gender, data = evals)
```

Step 2: Extract information from linear model object

```{r}
bty_score_info <- augment(bty_score_lm)
```

Step 3: Use residuals to check for normally distributed residuals

```{r}
bty_score_info %>% 
ggplot(aes(x = .resid)) +
  ## Remember that the column with the residuals in it is called ".resid". The period matters! 
  geom_histogram(binwidth = 0.2) +
  ## Change the binwidth to be appropriate for the distribution you have! 
  xlab("Residuals")
```

Step 4: Use residuals and fitted values to check for equal variance

```{r}
bty_score_info %>% 
ggplot(aes(x = .fitted, y = .resid)) +
  geom_point() +
  geom_hline(yintercept = 0, linetype = "dashed", color = "red") +
  ## The line above makes a dashed horizontal line at 0 and colors it red
  labs(x = "Fitted values", 
       y = "Residuals")
  ## The code above renames the x- and y-axis labels
```
