---
title: "Data Visualizations for Group Means"
output: ioslides_presentation
---

<style type="text/css">
slides > slide:not(.nobackground):after {
  content: '';
}
</style>

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = FALSE, 
                      message = FALSE)
library(tidyverse) 
library(palmerpenguins)
library(gridExtra)
```

## Distribution of Numerical Data 

</br>

- Histogram 

</br>

- Dotplot 

</br>

- Boxplot

</br>

- Density Plot

## Histogram

```{r, message = FALSE, fig.height = 4, fig.width = 4}
penguins %>% 
  ggplot(aes(x = bill_length_mm)) + 
  geom_histogram()
```


## Boxplot


```{r, fig.width = 4, fig.height = 4}
penguins %>% 
  ggplot(aes(x = bill_length_mm)) + 
  geom_boxplot()
```

## Density Plot 

```{r, fig.width = 4, fig.height = 4}
penguins %>% 
  ggplot(aes(x = bill_length_mm)) + 
  geom_density()
```

## Adding Groups 

__Side-by-Side Violins__  

```{r, fig.width = 4, fig.height = 3}
penguins %>% 
  ggplot(aes(x = bill_length_mm, y = species)) + 
  geom_violin(aes(fill = species)) + 
  theme(legend.position = "none")
```

## Faceted Histograms 

```{r, message = FALSE, fig.height = 3, fig.width = 8}
penguins %>% 
  ggplot(aes(x = bill_length_mm)) + 
  geom_histogram() + 
  facet_wrap(~species)
```



