---
title: "Untitled"
author: "Your Names Here!"
date: "10/26/2020"
output: html_document
---

```{r}
library(tidyverse)
library(openintro)
library(infer)
```

# Concept Discussion 

In a boostrap distribution we resample with replacement from our observed data the same number of times as samples in the original data. 

In a permutation distribution after shuffling the data we divide into groups with the same sample size as in the original data. 

If we were to change our sample size in the process of creating a bootstrap distribution, what would happen? 

If we were to change the size of the groups in the proces of creating a permutation distribtution, what would happen? 


# Think Out Loud Discussion

In the tutorials you learned how to create a permutation/randomization distribution and a bootstrap distribution. Specifically, you learned how to use tools from the infer package to create both of these distributions. Below is the code to create a permutation distribution and a bootstrap distribution in the context of the gender discrimination study. 

__Permutation__

`gender_discrimination %>% 
  specify(decision ~ gender, success = "promoted") %>% 
  hypothesize(null = "independence") %>% 
  generate(reps = 1000, type = "permute") %>% 
  calculate(stat = "diff in props", order = c("male", "female"))
`

__Boostrap__

`gender_discrimination %>% 
  specify(decision ~ gender, success = "promoted") %>% 
  generate(reps = 1000, type = "bootstrap") %>% 
  calculate(stat = "diff in props", order = c("male", "female"))
`
